<?php
namespace UserVoice;

/**
 * PHP version 5
 *
 * Generates a Single-Sign-On (SSO) token which you can add to a uservoice URL:
 * http://uservoice-subdomain.uservoice.com?sso=HERE
 *
 * If you experience difficulties with the SSO tokens generated by the function
 * below, you might have configured mbstring.func_overload other than 0. If so,
 * wrap the call to generate_sso_token like this:
 *
 *    $original_encoding = mb_internal_encoding();
 *    mb_internal_encodig('ASCII');
 *
 *    $sso_token = \UserVoice\SSO::generate_sso_token(...)
 *
 *    mb_internal_encoding($original_encoding);
 *
 *    // Now use the $sso_token
 *
 */
class SSO {

    public static function generate_token($subdomain_key, $sso_key, $user_hash, $valid_for = 300) {

        $salted = $sso_key . $subdomain_key;
        $key    = substr(sha1($salted, true), 0, 16);
        $iv     = "OpenSSL for Ruby";

        if ( ! array_key_exists('expires', $user_hash)) {
            $user_hash['expires'] = gmdate('Y-m-d H:i:s', time() + $valid_for);
        }

        $data = json_encode($user_hash);

        for ($i = 0; $i < 16; $i++) {
            $data[$i] = $data[$i] ^ $iv[$i];
        }

        $encrypted = openssl_encrypt($data, 'AES-128-CBC', $key, 0, $iv);

        return urlencode($encrypted);
    }
}

?>